const checkoutPage = {
    telephoneInputField: '#input-telephone',
    firstNameInputField: '#input-payment-firstname',
    lastNameInputField: '#input-payment-lastname',
    companyInputField: '#input-payment-company',
    adress1InputField: '#input-payment-address-1',
    adress2InputField: '#input-payment-address-2',
    cityInputField: '#input-payment-city',
    postCodeInputField: '#input-payment-postcode',
    countryInputField: '#input-payment-country',
    regionInputField: '#input-payment-zone',
    sameDeliveryAdressCheckbox: '#input-shipping-address-same',
    shippingMethod: '#shipping-method > .custom-control',
    imageTableCell: '#checkout-cart > .table > tbody > tr > .text-center',
    productNameTableCell: '#checkout-cart > .table > tbody > tr > :nth-child(2)',
    quantityInputField: '#quantity_13934',
    unitePriceTableCell: '#checkout-cart > .table > tbody > tr > :nth-child(4)',
    totalTableCell: 'tbody > tr > :nth-child(5)',
    updateCartButton: '.input-group-append > .btn-primary > .fas',
    removeFromCartButton: '.btn-danger > .fas',
    subTotalPriceTableCell: '#checkout-total > tbody > :nth-child(1) > .text-right > strong',
    shippingRateTableCell: '#checkout-total > tbody > :nth-child(2) > .text-right > strong',
    ecoTaxPriceTableCell: '#checkout-total > tbody > :nth-child(3) > .text-right > strong',
    vatPriceTableCell: '#checkout-total > tbody > :nth-child(4) > .text-right > strong',
    totalPriceTableCell: '#checkout-total > tbody > :nth-child(4) > .text-right > strong',
    commentInputField: '#input-comment',
    termsAndConditionsCheckbox: ':nth-child(6) > .custom-control-label',
    continueButton: '#button-save',
    shoppingCartLink: '.breadcrumb > .active'
}
export { checkoutPage }