const productComparisonPage = {
    product1: '.table > :nth-child(2) > :nth-child(1) > :nth-child(2)',
    image1: ':nth-child(2) > .img-thumbnail',
    price1: ':nth-child(2) > :nth-child(3) > :nth-child(2)',
    model1: ':nth-child(2) > :nth-child(4) > :nth-child(2)',
    brand1: ':nth-child(2) > :nth-child(5) > :nth-child(2)',
    availability1: ':nth-child(2) > :nth-child(6) > :nth-child(2)',
    rating1: ':nth-child(7) > :nth-child(2)',
    summary1: ':nth-child(8) > :nth-child(2)',
    weight1: ':nth-child(9) > :nth-child(2)',
    dimensions1: ':nth-child(10) > :nth-child(2)',
    clockspeedOrMemory1: ':nth-child(4) > tr > :nth-child(2)',
    addToCart1: 'tr > :nth-child(2) > .btn-primary',
    remove1: ':nth-child(2) > .btn-danger',
    cores1: ':nth-child(6) > tr > :nth-child(2)',

    product2: '.table > :nth-child(2) > :nth-child(1) > :nth-child(3)',
    image2: ':nth-child(3) > .img-thumbnail',
    price2: ':nth-child(2) > :nth-child(3) > :nth-child(3)',
    model2: ':nth-child(2) > :nth-child(4) > :nth-child(3)',
    brand2: ':nth-child(2) > :nth-child(5) > :nth-child(3)',
    availability2: ':nth-child(6) > :nth-child(3)',
    rating2: ':nth-child(7) > :nth-child(3)',
    summary2: ':nth-child(8) > :nth-child(3)',
    weight2: ':nth-child(9) > :nth-child(3)',
    dimensions2: ':nth-child(10) > :nth-child(3)',
    clockspeedOrMemory2: ':nth-child(4) > tr > :nth-child(3)',
    addToCart2: ':nth-child(3) > .btn-primary',
    remove2: ':nth-child(3) > .btn-danger',
    cores2: ':nth-child(6) > tr > :nth-child(3)',

    product3: '.table > :nth-child(2) > :nth-child(1) > :nth-child(4)',
    image3: ':nth-child(4) > .img-thumbnail',
    price3: ':nth-child(2) > :nth-child(3) > :nth-child(4)',
    model3: ':nth-child(2) > :nth-child(4) > :nth-child(4)',
    brand3: ':nth-child(2) > :nth-child(5) > :nth-child(4)',
    availability3: ':nth-child(6) > :nth-child(4)',
    rating3: ':nth-child(7) > :nth-child(4)',
    summary3: ':nth-child(8) > :nth-child(4)',
    weight3: ':nth-child(9) > :nth-child(4)',
    dimensions3: ':nth-child(10) > :nth-child(4)',
    clockspeedOrMemory3: ':nth-child(4) > tr > :nth-child(4)',
    addToCart3: ':nth-child(4) > .btn-primary',
    remove3: ':nth-child(4) > .btn-danger',
    cores3: ':nth-child(6) > tr > :nth-child(4)',

    product4: '.table > :nth-child(2) > :nth-child(1) > :nth-child(5)',
    image4: ':nth-child(5) > .img-thumbnail',
    price4: ':nth-child(2) > :nth-child(3) > :nth-child(5)',
    model4: ':nth-child(2) > :nth-child(4) > :nth-child(5)',
    brand4: ':nth-child(2) > :nth-child(5) > :nth-child(5)',
    availability4: ':nth-child(6) > :nth-child(5)',
    rating4: ':nth-child(7) > :nth-child(5)',
    summary4: ':nth-child(8) > :nth-child(5)',
    weight4: ':nth-child(9) > :nth-child(5)',
    dimensions4: ':nth-child(10) > :nth-child(5)',
    clockspeedOrMemory4: ':nth-child(4) > tr > :nth-child(5)',
    addToCart4: ':nth-child(5) > .btn-primary',
    remove4: ':nth-child(5) > .btn-danger',
    cores4: ':nth-child(6) > tr > :nth-child(5)',

    successMessage: '#product-compare > .alert'
}
export { productComparisonPage }