import { homePage, header, navigationBar, topTrending } from '../support/POM/homePage';
import { loginPage } from '../support/POM/loginPage';
import { registrationPage } from '../support/POM/registrationPage';
import { componentsPage } from '../support/POM/componentsPage';
import { cartPage } from '../support/POM/yourCartPage';
import { checkoutPage } from '../support/POM/checkoutPage';
import { myAccountPage } from '../support/POM/myAccountPage';
import { confirmOrderPage } from '../support/POM/confirmOrderPage';

describe('Buying products Flow Tests', () => {

    beforeEach('Visit url', () => {
        cy.visit('/')
      })
    afterEach('Logout', () => {
        cy.get(navigationBar.myAccountButton).click()
        cy.get(myAccountPage.logoutButton).click()
      })

it('Adding items to the cart', () => {
        cy.get(navigationBar.myAccountButton).click()
        cy.url().should('include', '/index.php?route=account/login')
        cy.get(loginPage.continueButton).click()
        cy.url().should('include', '/index.php?route=account/register')
        cy.get(registrationPage.firstNameField).type('Boban')
        cy.get(registrationPage.lastNameField).type('Rajovic')
        cy.get(registrationPage.emailField).type('bobanrajovic@101.rs')
        cy.get(registrationPage.telephoneField).type('+38268051011')
        cy.get(registrationPage.passwordField).type('usnebojevina123')
        cy.get(registrationPage.passwordConfirmField).type('usnebojevina123')
        cy.get(registrationPage.subscribeYes).click()
        cy.get(registrationPage.privacyPolicy).click()
        cy.get(registrationPage.continueButton).click()
        cy.url().should('include', '/index.php?route=account/success')
        cy.get('.page-title').should('contain', 'Your Account Has Been Created!')
        cy.get(registrationPage.continueButtonAfter).click()
        cy.url().should('include', '/index.php?route=account/account')
        cy.get(navigationBar.homeButton).click()
        cy.url().should('include', '/index.php?route=common/home')
        cy.get(topTrending.category3).click()
        cy.url().should('include', '/index.php?route=product/category&path=25')
        cy.get(componentsPage.product).eq(4).realHover()
        cy.get(componentsPage.productAction).should('exist')
        cy.get(componentsPage.cartButtonProductAction).eq(4).click()
        cy.get(componentsPage.notificationProductaAdded).should('exist')
    })
it('Product is added to the cart, quantity and price correct', () => {
        cy.get(navigationBar.myAccountButton).click()
        cy.url().should('include', '/index.php?route=account/login')
        cy.get(loginPage.emailField).type('bobanrajovic@011.rs')
        cy.get(loginPage.passwordField).type('usnebojevina123')
        cy.get(loginPage.loginButton).click()
        cy.get(navigationBar.homeButton).click()
        cy.url().should('include', '/index.php?route=common/home')
        cy.get(topTrending.category3).click()
        cy.url().should('include', '/index.php?route=product/category&path=25')
        cy.get(componentsPage.product).eq(1).realHover()
        cy.get(componentsPage.productAction).should('exist')
        cy.get(componentsPage.cartButtonProductAction).eq(1).click()
        cy.get(componentsPage.notificationProductaAdded).should('exist')
        cy.get(componentsPage.notificationViewCartButton).click()
        cy.url().should('include', 'index.php?route=checkout/cart')
        cy.get(cartPage.imageTableCell).should('have.attr', 'alt', 'Palm Treo Pro')
        cy.get(cartPage.productNameTableCell).should('have.text', 'Palm Treo Pro ')
        cy.get(cartPage.modelTableCell).should('have.text', 'Product 2')
        cy.get(cartPage.quantityInputField).should('have.value', '1')
        cy.get(cartPage.uniteTableCell).should('have.text','$279.99')
        cy.get(cartPage.totalTableCell).should('have.text','$279.99')
        cy.get(cartPage.subTotalPriceTableCell).should('have.text', '$279.99')
        cy.get(cartPage.totalPriceTableCell).should('have.text', '$279.99')
        cy.get(cartPage.checkoutButton).click()
        cy.url().should('include', '/index.php?route=checkout/checkout')
        cy.get(checkoutPage.shoppingCartLink).click()
        cy.get(cartPage.removeFromCartButton).click()
        cy.get(cartPage.emptyCartContinueButton).click()
    })
it.only('Complete the order', () => {
    cy.get(navigationBar.myAccountButton).click()
        cy.url().should('include', '/index.php?route=account/login')
        cy.get(loginPage.emailField).type('bobanrajovic@011.rs')
        cy.get(loginPage.passwordField).type('usnebojevina123')
        cy.get(loginPage.loginButton).click()
        cy.get(navigationBar.homeButton).click()
        cy.url().should('include', '/index.php?route=common/home')
        cy.get(topTrending.category3).click()
        cy.url().should('include', '/index.php?route=product/category&path=25')
        cy.get(componentsPage.product).eq(1).realHover()
        cy.get(componentsPage.productAction).should('exist')
        cy.get(componentsPage.cartButtonProductAction).eq(1).click()
        cy.get(componentsPage.notificationProductaAdded).should('exist')
        cy.get(componentsPage.notificationViewCartButton).click()
        cy.url().should('include', 'index.php?route=checkout/cart')
        cy.get(cartPage.imageTableCell).should('have.attr', 'alt', 'Palm Treo Pro')
        cy.get(cartPage.productNameTableCell).should('have.text', 'Palm Treo Pro ')
        cy.get(cartPage.modelTableCell).should('have.text', 'Product 2')
        cy.get(cartPage.quantityInputField).should('have.value', '1')
        cy.get(cartPage.uniteTableCell).should('have.text','$279.99')
        cy.get(cartPage.totalTableCell).should('have.text','$279.99')
        cy.get(cartPage.subTotalPriceTableCell).should('have.text', '$279.99')
        cy.get(cartPage.totalPriceTableCell).should('have.text', '$279.99')
        cy.get(cartPage.checkoutButton).click()
        cy.url().should('include', '/index.php?route=checkout/checkout')
        cy.get(checkoutPage.telephoneInputField).should('have.value', '+38268051011')
        cy.get(checkoutPage.sameDeliveryAdressCheckbox).should('be.checked')
        cy.get(checkoutPage.termsAndConditionsCheckbox).click()
        cy.get(checkoutPage.continueButton).click()
        cy.get(confirmOrderPage.confirmOrderButton).click()
        cy.url().should('include', '/index.php?route=checkout/success')
        cy.get(registrationPage.continueButtonAfter).click()
    })
})