import { myAccountPage } from '../support/POM/myAccountPage';
import { navigationBar, topProducts } from '../support/POM/homePage';
import { loginPage } from '../support/POM/loginPage';
import { componentsPage } from '../support/POM/componentsPage';
import { productComparisonPage } from '../support/POM/productComparisonPage';

describe('Compare products function Tests', () => {

    beforeEach('Visit url and login', () => {
        cy.visit('/')
        cy.get(navigationBar.myAccountButton).click()
        cy.url().should('include', '/index.php?route=account/login')
        cy.get(loginPage.emailField).type('bobanrajovic@011.rs')
        cy.get(loginPage.passwordField).type('usnebojevina123')
        cy.get(loginPage.loginButton).click()
      })
    afterEach('Logout', () => {
        cy.get(navigationBar.myAccountButton).click()
        cy.get(myAccountPage.logoutButton).click()
      })

    it('Compare two products test', () => {
        cy.get(navigationBar.homeButton).click()
        cy.url().should('include', '/index.php?route=common/home')
        cy.get(topProducts.product7).eq(0).realHover()
        cy.get(componentsPage.productAction, { timeout: 10000 }).should('be.visible')
        cy.get(componentsPage.compareProductsButton).eq(6).click({force: true})
        cy.get(topProducts.product9).eq(0).realHover()
        cy.get(componentsPage.productAction).should('exist')
        cy.get(componentsPage.compareProductsButton).eq(8).click({force: true})
        cy.get(componentsPage.notificationProductaAdded,{ timeout: 10000 }).should('be.visible')
        cy.get(componentsPage.notificationCompareButton).click()
        cy.url().should('include', '/index.php?route=product/compare')
        cy.get(productComparisonPage.product1).should('have.text','HTC Touch HD')
        cy.get(productComparisonPage.image1).should('have.attr', 'alt', 'HTC Touch HD')
        cy.get(productComparisonPage.price1).should('have.text',' $120.00\n')
        cy.get(productComparisonPage.model1).should('have.text','Product 1')
        cy.get(productComparisonPage.brand1).should('have.text','HTC')
        cy.get(productComparisonPage.availability1).should('have.text','In Stock')
        cy.get(productComparisonPage.rating1).should('have.text','       Based on 0 reviews.')
        cy.get(productComparisonPage.summary1).should('contain','HTC Touch - in High Definition.')
        cy.get(productComparisonPage.weight1).should('have.text','146.40g')
        cy.get(productComparisonPage.dimensions1).should('have.text','0.00cm x 0.00cm x 0.00cm')
        cy.get(productComparisonPage.clockspeedOrMemory1).should('have.text','')
        cy.get(productComparisonPage.cores1).should('have.text','')
        cy.get(productComparisonPage.product2).should('have.text','HP LP3065')
        cy.get(productComparisonPage.image2).should('have.attr', 'alt', 'HP LP3065')
        cy.get(productComparisonPage.price2).should('have.text',' $100.00\n')
        cy.get(productComparisonPage.model2).should('have.text','Product 21')
        cy.get(productComparisonPage.brand2).should('have.text','Hewlett-Packard')
        cy.get(productComparisonPage.availability2).should('have.text','In Stock')
        cy.get(productComparisonPage.rating2).should('have.text','       Based on 0 reviews.')
        cy.get(productComparisonPage.summary2).should('contain',' 30-inch diagonal HP LP3065 Flat Panel Monitor. This flagship monitor features best-in-class performance')
        cy.get(productComparisonPage.weight2).should('have.text','1.00kg')
        cy.get(productComparisonPage.dimensions2).should('have.text','0.00cm x 0.00cm x 0.00cm')
        cy.get(productComparisonPage.clockspeedOrMemory2).should('have.text',' 16GB')
        cy.get(productComparisonPage.cores2).should('have.text',' 4')
    })
    it('Compare four products test', () => {
        cy.get(navigationBar.homeButton).click()
        cy.url().should('include', '/index.php?route=common/home')
        cy.get(topProducts.product7).eq(0).realHover()
        cy.get(componentsPage.productAction, { timeout: 10000 }).should('be.visible')
        cy.get(componentsPage.compareProductsButton).eq(6).click({force: true})
        cy.get(topProducts.product9).eq(0).realHover()
        cy.get(componentsPage.productAction).should('exist')
        cy.get(componentsPage.compareProductsButton).eq(8).click({force: true})
        cy.get(topProducts.product1).eq(0).realHover()
        cy.get(componentsPage.productAction, { timeout: 10000 }).should('be.visible')
        cy.get(componentsPage.compareProductsButton).eq(0).click({force: true})
        cy.get(topProducts.product10).eq(0).realHover()
        cy.get(componentsPage.productAction).should('exist')
        cy.get(componentsPage.compareProductsButton).eq(9).click({force: true})
        cy.get(componentsPage.notificationProductaAdded,{ timeout: 10000 }).should('be.visible')
        cy.get(componentsPage.notificationCompareButton).eq(0).click()
        cy.url().should('include', '/index.php?route=product/compare')
        cy.get(productComparisonPage.product1).should('have.text','HTC Touch HD')
        cy.get(productComparisonPage.image1).should('have.attr', 'alt', 'HTC Touch HD')
        cy.get(productComparisonPage.price1).should('have.text',' $120.00\n')
        cy.get(productComparisonPage.model1).should('have.text','Product 1')
        cy.get(productComparisonPage.brand1).should('have.text','HTC')
        cy.get(productComparisonPage.availability1).should('have.text','In Stock')
        cy.get(productComparisonPage.rating1).should('have.text','       Based on 0 reviews.')
        cy.get(productComparisonPage.summary1).should('contain','HTC Touch - in High Definition.')
        cy.get(productComparisonPage.weight1).should('have.text','146.40g')
        cy.get(productComparisonPage.dimensions1).should('have.text','0.00cm x 0.00cm x 0.00cm')
        cy.get(productComparisonPage.clockspeedOrMemory1).should('have.text','')
        cy.get(productComparisonPage.cores1).should('have.text','')
        cy.get(productComparisonPage.product2).should('have.text','HP LP3065')
        cy.get(productComparisonPage.image2).should('have.attr', 'alt', 'HP LP3065')
        cy.get(productComparisonPage.price2).should('have.text',' $100.00\n')
        cy.get(productComparisonPage.model2).should('have.text','Product 21')
        cy.get(productComparisonPage.brand2).should('have.text','Hewlett-Packard')
        cy.get(productComparisonPage.availability2).should('have.text','In Stock')
        cy.get(productComparisonPage.rating2).should('have.text','       Based on 0 reviews.')
        cy.get(productComparisonPage.summary2).should('contain',' 30-inch diagonal HP LP3065 Flat Panel Monitor. This flagship monitor features best-in-class performance')
        cy.get(productComparisonPage.weight2).should('have.text','1.00kg')
        cy.get(productComparisonPage.dimensions2).should('have.text','0.00cm x 0.00cm x 0.00cm')
        cy.get(productComparisonPage.clockspeedOrMemory2).should('have.text',' 16GB')
        cy.get(productComparisonPage.cores2).should('have.text',' 4')
        cy.get(productComparisonPage.product3).should('have.text','iMac')
        cy.get(productComparisonPage.image3).should('have.attr', 'alt', 'iMac')
        cy.get(productComparisonPage.price3).should('have.text',' $140.00\n')
        cy.get(productComparisonPage.model3).should('have.text','Product 14')
        cy.get(productComparisonPage.brand3).should('have.text','Apple')
        cy.get(productComparisonPage.availability3).should('have.text','In Stock')
        cy.get(productComparisonPage.rating3).should('have.text','       Based on 0 reviews.')
        cy.get(productComparisonPage.summary3).should('contain',' More powerful Intel Core 2 Duo processors. And more memory standard.')
        cy.get(productComparisonPage.weight3).should('have.text','5.00kg')
        cy.get(productComparisonPage.dimensions3).should('have.text','0.00cm x 0.00cm x 0.00cm')
        cy.get(productComparisonPage.clockspeedOrMemory3).should('have.text','')
        cy.get(productComparisonPage.cores3).should('have.text','')
        cy.get(productComparisonPage.product4).should('have.text','HP LP3065')
        cy.get(productComparisonPage.image4).should('have.attr', 'alt', 'HP LP3065')
        cy.get(productComparisonPage.price4).should('have.text',' $100.00\n')
        cy.get(productComparisonPage.model4).should('have.text','Product 21')
        cy.get(productComparisonPage.brand4).should('have.text','Hewlett-Packard')
        cy.get(productComparisonPage.availability4).should('have.text','In Stock')
        cy.get(productComparisonPage.rating4).should('have.text','       Based on 0 reviews.')
        cy.get(productComparisonPage.summary4).should('contain','This flagship monitor features best-in-class')
        cy.get(productComparisonPage.weight4).should('have.text','1.00kg')
        cy.get(productComparisonPage.dimensions4).should('have.text','0.00cm x 0.00cm x 0.00cm')
        cy.get(productComparisonPage.clockspeedOrMemory4).should('have.text',' 16GB')
        cy.get(productComparisonPage.cores4).should('have.text',' 4')
    })
    it('Add to cart and remove buttons when comparing', () => {
        cy.get(navigationBar.homeButton).click()
        cy.url().should('include', '/index.php?route=common/home')
        cy.get(topProducts.product7).eq(0).realHover()
        cy.get(componentsPage.productAction, { timeout: 10000 }).should('be.visible')
        cy.get(componentsPage.compareProductsButton).eq(6).click({force: true})
        cy.get(topProducts.product9).eq(0).realHover()
        cy.get(componentsPage.productAction).should('exist')
        cy.get(componentsPage.compareProductsButton).eq(8).click({force: true})
        cy.get(componentsPage.notificationProductaAdded,{ timeout: 10000 }).should('be.visible')
        cy.get(componentsPage.notificationCompareButton).click()
        cy.url().should('include', '/index.php?route=product/compare')
        cy.get(productComparisonPage.product1).should('have.text','HTC Touch HD')
        cy.get(productComparisonPage.image1).should('have.attr', 'alt', 'HTC Touch HD')
        cy.get(productComparisonPage.price1).should('have.text',' $120.00\n')
        cy.get(productComparisonPage.model1).should('have.text','Product 1')
        cy.get(productComparisonPage.brand1).should('have.text','HTC')
        cy.get(productComparisonPage.availability1).should('have.text','In Stock')
        cy.get(productComparisonPage.rating1).should('have.text','       Based on 0 reviews.')
        cy.get(productComparisonPage.summary1).should('contain','HTC Touch - in High Definition.')
        cy.get(productComparisonPage.weight1).should('have.text','146.40g')
        cy.get(productComparisonPage.dimensions1).should('have.text','0.00cm x 0.00cm x 0.00cm')
        cy.get(productComparisonPage.clockspeedOrMemory1).should('have.text','')
        cy.get(productComparisonPage.cores1).should('have.text','')
        cy.get(productComparisonPage.product2).should('have.text','HP LP3065')
        cy.get(productComparisonPage.image2).should('have.attr', 'alt', 'HP LP3065')
        cy.get(productComparisonPage.price2).should('have.text',' $100.00\n')
        cy.get(productComparisonPage.model2).should('have.text','Product 21')
        cy.get(productComparisonPage.brand2).should('have.text','Hewlett-Packard')
        cy.get(productComparisonPage.availability2).should('have.text','In Stock')
        cy.get(productComparisonPage.rating2).should('have.text','       Based on 0 reviews.')
        cy.get(productComparisonPage.summary2).should('contain',' 30-inch diagonal HP LP3065 Flat Panel Monitor. This flagship monitor features best-in-class performance')
        cy.get(productComparisonPage.weight2).should('have.text','1.00kg')
        cy.get(productComparisonPage.dimensions2).should('have.text','0.00cm x 0.00cm x 0.00cm')
        cy.get(productComparisonPage.clockspeedOrMemory2).should('have.text',' 16GB')
        cy.get(productComparisonPage.cores2).should('have.text',' 4')
        cy.get(productComparisonPage.addToCart1).click()
        cy.get(componentsPage.notificationProductaAdded,{ timeout: 10000 }).should('be.visible')
        cy.get(productComparisonPage.remove2).click()
        cy.get(productComparisonPage.successMessage,{ timeout: 10000 }).should('exist')
        .and('have.text', ' Success: You have modified your product comparison!\n× ')
        .and('have.css', 'background-color', 'rgb(212, 237, 218)')
    })
})