describe('Frontend Homepage Test', () => {
  it('homepageElements', () => {
    cy.visit('/')
    cy.get('#main-header')
      .should('exist')
    cy.get('#entry_217833')
      .should('exist')
    cy.get('#widget-navbar-217834')
      .should('exist')
    cy.get('.active > a.d-block > .d-block')
      .should('exist')
    cy.get('#entry_213241')
      .should('exist')
    cy.get('#entry_213248')
      .should('exist')
    cy.get('#entry_213254')
      .should('exist')
    cy.get('#entry_213257')
      .should('exist')
    cy.get('#entry_213260')
      .should('exist')
    cy.get('#entry_213263')
      .should('exist')
    cy.get('#mz-product-listing-39213264 > .mz-tab-listing-header')
      .should('exist')
    cy.get('#mz-product-tab-39213264-0 > .swiper')
      .should('exist')
    cy.get('#entry_213265 > .d-block > .hover-effect > .lazy-load')
      .should('exist')
    cy.get('#entry_213268')
      .should('exist')
    cy.get('#entry_213270')
      .should('exist')
    cy.get('#entry_213272')
     .should('exist')
    cy.get('#entry_217558')
      .should('exist')
    cy.get('#back-to-top')
      .should('exist')
  })

})