import { homePage, header, navigationBar } from '../support/POM/homepage' ;

describe('Frontend Homepage Tests', () => {
  it('homepageElements', () => {
    cy.visit('/')
    cy.get(homePage.header)
      .should('exist')
    cy.get(homePage.navigationBar)
      .should('exist')
    cy.get(homePage.mainBanner)
      .should('exist')
    cy.get(homePage.promoSection1)
      .should('exist')
    cy.get(homePage.topTrendingCategories)
      .should('exist')
    cy.get(homePage.dealsOfTheDay)
      .should('exist')
    cy.get(homePage.topProducts)
      .should('exist')
    cy.get(homePage.promoSection2)
      .should('exist')
    cy.get(homePage.specialOffer)
      .should('exist')
    cy.get(homePage.topCollectionPart1)
      .should('exist')
    cy.get(homePage.topCollectionPart2)
      .should('exist')
    cy.get(homePage.promoBanner)
      .should('exist')
    cy.get(homePage.under99)
      .should('exist')
    cy.get(homePage.fromTheBlog)
     .should('exist')
    cy.get(homePage.footer)
      .should('exist')
    cy.get(homePage.backToTopButton)
      .should('exist')
  })

  it('headerElements', () => {
    cy.visit('/')
    cy.get(header.siteLogoButton)
      .should('exist')
    cy.get(header.allCategoriesDropdown)
      .should('exist')
    cy.get(header.searchBar)
      .should('exist')
    cy.get(header.searchIcon)
      .should('exist')
    cy.get(header.compareIcon)
      .should('exist')
    cy.get(header.wishlistIcon)
      .should('exist')
    cy.get(header.cartIcon)
      .should('exist')
  })

  it('siteLogoButton', () => {
    cy.visit('/')
    cy.get(header.siteLogoButton)
      .should('exist')
    cy.get(navigationBar.blogButton).click()
    cy.url()
      .should('include', '/index.php?route=extension/maza/blog/home')
    cy.get(header.siteLogoButton).click()
    cy.url()
      .should('include', '/index.php?route=common/home')
  })

})